packages:
  - packages/**
  - '!**/test/**'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - unrs-resolver

overrides:
  '@babel/runtime@<7.26.10': '>=7.26.10'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  braces@<3.0.3: '>=3.0.3'
  cross-spawn@>=7.0.0 <7.0.5: '>=7.0.5'
  follow-redirects@<=1.15.5: '>=1.15.6'
  micromatch@<4.0.8: '>=4.0.8'
  nanoid@<3.3.8: '>=3.3.8'
  on-headers@<1.1.0: '>=1.1.0'
